name: React CI

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Docker image
        run: docker build -t simple-web-app:latest .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: docker tag simple-web-app:latest danu2809/simple-web-app:latest
        
      - name: Push Docker image
        run: docker push danu2809/simple-web-app:latest